version: "3"

services: 
  server:
    build: .
    container_name: NODEJS_RANK
    command: npm start
    volumes: 
      - .:/usr/server
    environment: 
      NODE_ENV: development
    depends_on: 
      - mongo
    links: 
      - mongo
    ports: 
      - "3000:3000"
  mongo:
    container_name: MONGO_RANK
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports: 
      - "27017:27017"
