version: "3"

services: 
  node-server:
    depends_on: 
      - mongodb
    container_name: node-server
    build: 
      context: .
    volumes: 
      - .:/usr/src/server
    command: npm start
    links: 
      - mongodb:mongodb
    ports: 
      - 3000:3000

  mongodb:
    container_name: mongo-rank
    image: mongo
    volumes:
      - ./data/database:/data/db
    ports: 
      - 27017:27017
